### ISSUE TITLE
question about re-implement

### ISSUE THREAD

**Issue by wudapeng268** [salman1993/simple-qa-on-kb#46]
Hi everyone:
Do you try to re-implement "Simple Question Answering by Attentive Convolutional Neural Network" this paper?

Thanks

**Comment by Impavidity** [comment]
Hi, I have one implementation for the attentive cnn. However, it does not get the performance as I expected because we do not have good results on entity linking part, which cause the error propagation problem. But I think the model.py file would helpful to you in some way. This is the link https://github.com/Impavidity/attentive_cnn . Because there are no documents for this repo, if you have any problem, please let me know.

**Comment by zjjj** [comment]
thanks for sharing this project.

About the attentive_cnn baseline above, could you please give me some basic introductions on how to get the program up running? I renamed "./data/sample.attentivecnn.train[valid|test]" to  "./data/attentivecnn.train[valid|test]", but then the following error:
```
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    train, dev, test = SimpleQADataset.splits(ID, WORD, CHAR, SCORE, LABEL)
ValueError: not enough values to unpack (expected 3, got 2)

```
And also, running the "setup.sh" in BuboQA repo really takes a long time (it has been running for 24 hours for me). Any estimation on how long it would usually take? I am stuck here:
```
Running create_indexes script...

mkdir: cannot create directory ‘indexes’: File exists


Create the reachability index for 2M-freebase-subset...

Freebase subset: data/SimpleQuestions_v2/freebase-subsets/freebase-FB2M.txt
Pickle output: indexes/reachability_2M.pkl
creating the index map...
line: 0
line: 1000000
line: 2000000
line: 3000000
```
Thanks!

**Comment by Impavidity** [comment]
@zjjj Thanks for your interest in the attentive cnn implementation. I will try to refine that implementation these days. I think that error is from the version changes of the torchtext. Because the API implementation of torchtext is changing.
For the indexing part, I will check this and get back to you soon.

**Comment by zjjj** [comment]
@Impavidity Thanks much! 
I think the indexing part may come from the "FB5M.name.txt" issue, as we discussed in another thread. I am running "create_index_reachability.py" at this moment, and I will let you know if I saw further issues.

**Comment by zjjj** [comment]
Just a suggestion, make the following changes to `scripts/create_index_reachabilitt.py` as shown below:
```
            # if subject in index.keys():  # NOTE: replace this line with the following
            if subject in index:
                index[subject].add(predicate)
            else:
                index[subject] = set([predicate])
```
This will significantly speed up the program. `index.keys()` returns a list, and looking up subject in that list takes linear time, whereas `... in index` uses a hash function and only takes time O(1).

The same modification can be applied to other preprocessing scripts as well.

**Comment by Impavidity** [comment]
@zjjj Thanks for your suggestions. We will try to improve the efficiency of the code !

**Comment by Buzaabah** [comment]
When I try to implement the above https://github.com/Impavidity/attentive_cnn  I get an Attribute error below. Anything I missing our?
AttributeError: module 'torchtext.data' has no attribute 'TabularDataset'
